// <auto-generated />
using System;
using ERP.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP.Repositories.Migrations
{
    [DbContext(typeof(ERPDBContext))]
    partial class ERPDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERP.Domain.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "USER-ADMIN-0001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ADMIN-CONCURRENCY-STAMP",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@erp.com",
                            EmailConfirmed = true,
                            FullName = "System Administrator",
                            IsActive = true,
                            JobTitle = "System Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ERP.COM",
                            NormalizedUserName = "ADMIN@ERP.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFUfno0apiyLD/H8ltTclkliznkIZH6rI8yl1YGS1dU1uThxbTPavE4cAWJGQzVzQA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ADMIN-SECURITY-STAMP",
                            TwoFactorEnabled = false,
                            UserName = "admin@erp.com"
                        },
                        new
                        {
                            Id = "USER-SALES-0001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "SALES-CONCURRENCY-STAMP",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sarah.sales@erp.com",
                            EmailConfirmed = true,
                            FullName = "Sarah Johnson",
                            IsActive = true,
                            JobTitle = "Sales Representative",
                            LockoutEnabled = false,
                            NormalizedEmail = "SARAH.SALES@ERP.COM",
                            NormalizedUserName = "SARAH.SALES@ERP.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAVnV/2QHL/X98hyikRM3G8yaVl6aDRp4DQgPcZklWl+0fSaDqUpfxYwIhC9Ru75Nw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "SALES-SECURITY-STAMP",
                            TwoFactorEnabled = false,
                            UserName = "sarah.sales@erp.com"
                        },
                        new
                        {
                            Id = "USER-WARE-0001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "WARE-CONCURRENCY-STAMP",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mike.warehouse@erp.com",
                            EmailConfirmed = true,
                            FullName = "Mike Thompson",
                            IsActive = true,
                            JobTitle = "Warehouse Manager",
                            LockoutEnabled = false,
                            NormalizedEmail = "MIKE.WAREHOUSE@ERP.COM",
                            NormalizedUserName = "MIKE.WAREHOUSE@ERP.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFyCBJ7rkekCduH/qr+5QFx4ffatRF1x6/ci9RnMQMnfVdDqhe7z0PoAJtiWIYarhQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "WARE-SECURITY-STAMP",
                            TwoFactorEnabled = false,
                            UserName = "mike.warehouse@erp.com"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Electronic devices and accessories",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stationery, paper, and office essentials",
                            Name = "Office Supplies"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Office and home furniture",
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Networking hardware and cables",
                            Name = "Networking"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Software products and license keys",
                            Name = "Software & Licenses"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "12 Nile St, Cairo",
                            CreatedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice@example.com",
                            Name = "Alice Morgan",
                            Phone = "01001234567"
                        },
                        new
                        {
                            Id = 2,
                            Address = "45 Pyramids Ave, Giza",
                            CreatedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob@example.com",
                            Name = "Bob Carter",
                            Phone = "01011234567"
                        },
                        new
                        {
                            Id = 3,
                            Address = "7 Tahrir Sq, Cairo",
                            CreatedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "clara@example.com",
                            Name = "Clara Stone",
                            Phone = "01021234567"
                        },
                        new
                        {
                            Id = 4,
                            Address = "33 Corniche Rd, Alexandria",
                            CreatedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "david@example.com",
                            Name = "David Hale",
                            Phone = "01031234567"
                        },
                        new
                        {
                            Id = 5,
                            Address = "88 October City, Giza",
                            CreatedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "eva@example.com",
                            Name = "Eva Nguyen",
                            Phone = "01041234567"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Models.InventoryLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("PurchaseId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("InventoryLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "USER-WARE-0001",
                            ProductId = 1,
                            PurchaseId = 1,
                            Quantity = 50,
                            Type = "In"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "USER-WARE-0001",
                            ProductId = 2,
                            PurchaseId = 2,
                            Quantity = 50,
                            Type = "In"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "USER-SALES-0001",
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = -1,
                            Type = "Out"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "USER-SALES-0001",
                            OrderId = 2,
                            ProductId = 2,
                            Quantity = -2,
                            Type = "Out"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "USER-WARE-0001",
                            ProductId = 3,
                            Quantity = -3,
                            Type = "Adjustment"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "USER-SALES-0001",
                            CustomerId = 1,
                            IsDeleted = false,
                            OrderDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaidAmount = 1099.99m,
                            PaymentStatus = "Paid",
                            Status = "Completed",
                            TotalAmount = 1099.99m,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "USER-SALES-0001",
                            CustomerId = 2,
                            IsDeleted = false,
                            OrderDate = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaidAmount = 300.00m,
                            PaymentStatus = "Partial",
                            Status = "Pending",
                            TotalAmount = 599.98m,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "USER-SALES-0001",
                            CustomerId = 3,
                            IsDeleted = false,
                            OrderDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaidAmount = 0m,
                            PaymentStatus = "Pending",
                            Status = "Pending",
                            TotalAmount = 399.99m,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "USER-SALES-0001",
                            CustomerId = 4,
                            IsDeleted = false,
                            OrderDate = new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaidAmount = 179.99m,
                            PaymentStatus = "Paid",
                            Status = "Completed",
                            TotalAmount = 179.99m,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "USER-SALES-0001",
                            CustomerId = 5,
                            IsDeleted = false,
                            OrderDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaidAmount = 0m,
                            PaymentStatus = "Pending",
                            Status = "Cancelled",
                            TotalAmount = 59.99m,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ERP.Domain.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 1099.99m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 2,
                            ProductId = 2,
                            Quantity = 2,
                            UnitPrice = 299.99m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 3,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 399.99m
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 4,
                            ProductId = 5,
                            Quantity = 1,
                            UnitPrice = 179.99m
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 5,
                            ProductId = 4,
                            Quantity = 1,
                            UnitPrice = 59.99m
                        });
                });

            modelBuilder.Entity("ERP.Domain.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1099.99m,
                            CustomerId = 1,
                            OrderId = 1,
                            PaymentDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "Card"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 300.00m,
                            CustomerId = 2,
                            OrderId = 2,
                            PaymentDate = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "Cash"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 150.00m,
                            CustomerId = 2,
                            OrderId = 2,
                            PaymentDate = new DateTime(2025, 2, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "Transfer"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 179.99m,
                            CustomerId = 4,
                            OrderId = 4,
                            PaymentDate = new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "Card"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 100.00m,
                            CustomerId = 3,
                            OrderId = 3,
                            PaymentDate = new DateTime(2025, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "Cash"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CostPrice = 750.00m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Image = "dell-laptop.jpg",
                            Name = "Dell Laptop 15\"",
                            SKU = "ELEC-001",
                            SellingPrice = 1099.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CostPrice = 180.00m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Image = "hp-monitor.jpg",
                            Name = "HP Monitor 24\"",
                            SKU = "ELEC-002",
                            SellingPrice = 299.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CostPrice = 220.00m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Image = "office-chair.jpg",
                            Name = "Ergonomic Office Chair",
                            SKU = "FURN-001",
                            SellingPrice = 399.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CostPrice = 35.00m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Image = "tp-switch.jpg",
                            Name = "TP-Link 8-Port Switch",
                            SKU = "NET-001",
                            SellingPrice = 59.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            CostPrice = 100.00m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Image = "ms-office.jpg",
                            Name = "Microsoft Office 2024 Key",
                            SKU = "SOFT-001",
                            SellingPrice = 179.99m,
                            StockQuantity = 100
                        });
                });

            modelBuilder.Entity("ERP.Domain.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Purchases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "USER-WARE-0001",
                            PurchaseDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Received",
                            SupplierId = 1,
                            TotalAmount = 37500.00m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "USER-WARE-0001",
                            PurchaseDate = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Received",
                            SupplierId = 2,
                            TotalAmount = 9000.00m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "USER-WARE-0001",
                            PurchaseDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Received",
                            SupplierId = 3,
                            TotalAmount = 6600.00m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "USER-WARE-0001",
                            PurchaseDate = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Received",
                            SupplierId = 4,
                            TotalAmount = 2100.00m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "USER-WARE-0001",
                            PurchaseDate = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Pending",
                            SupplierId = 5,
                            TotalAmount = 10000.00m
                        });
                });

            modelBuilder.Entity("ERP.Domain.Models.PurchaseItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("PurchaseItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            PurchaseId = 1,
                            Quantity = 50,
                            UnitCost = 750.00m
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 2,
                            PurchaseId = 2,
                            Quantity = 50,
                            UnitCost = 180.00m
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 3,
                            PurchaseId = 3,
                            Quantity = 30,
                            UnitCost = 220.00m
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 4,
                            PurchaseId = 4,
                            Quantity = 60,
                            UnitCost = 35.00m
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 5,
                            PurchaseId = 5,
                            Quantity = 100,
                            UnitCost = 100.00m
                        });
                });

            modelBuilder.Entity("ERP.Domain.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Industrial Zone A, Cairo",
                            CreatedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sales@techsource.com",
                            Name = "TechSource LLC",
                            Phone = "01101234567"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Free Zone, Alexandria",
                            CreatedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "orders@globaldepot.com",
                            Name = "Global Office Depot",
                            Phone = "01111234567"
                        },
                        new
                        {
                            Id = 3,
                            Address = "New Cairo, Cairo",
                            CreatedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "info@furnipro.eg",
                            Name = "FurniPro Egypt",
                            Phone = "01121234567"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Smart Village, Giza",
                            CreatedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "support@netgearab.com",
                            Name = "NetGear Arabia",
                            Phone = "01131234567"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Downtown, Cairo",
                            CreatedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "licenses@softdist.com",
                            Name = "SoftDist International",
                            Phone = "01141234567"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ROLE-ADMIN-0001",
                            ConcurrencyStamp = "ROLE-ADMIN-STAMP",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "ROLE-SALES-0001",
                            ConcurrencyStamp = "ROLE-SALES-STAMP",
                            Name = "SalesEmployee",
                            NormalizedName = "SALESEMPLOYEE"
                        },
                        new
                        {
                            Id = "ROLE-WARE-0001",
                            ConcurrencyStamp = "ROLE-WARE-STAMP",
                            Name = "WarehouseEmployee",
                            NormalizedName = "WAREHOUSEEMPLOYEE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "USER-ADMIN-0001",
                            RoleId = "ROLE-ADMIN-0001"
                        },
                        new
                        {
                            UserId = "USER-SALES-0001",
                            RoleId = "ROLE-SALES-0001"
                        },
                        new
                        {
                            UserId = "USER-WARE-0001",
                            RoleId = "ROLE-WARE-0001"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ERP.Domain.Models.InventoryLog", b =>
                {
                    b.HasOne("ERP.Domain.Models.ApplicationUser", "CreatedByUser")
                        .WithMany("InventoryLogs")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");

                    b.HasOne("ERP.Domain.Models.Product", "Product")
                        .WithMany("InventoryLogs")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Models.Purchase", "Purchase")
                        .WithMany()
                        .HasForeignKey("PurchaseId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("ERP.Domain.Models.Order", b =>
                {
                    b.HasOne("ERP.Domain.Models.ApplicationUser", "CreatedByUser")
                        .WithMany("Orders")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ERP.Domain.Models.OrderItem", b =>
                {
                    b.HasOne("ERP.Domain.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Models.Product", "Product")
                        .WithMany("OrderItem")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ERP.Domain.Models.Payment", b =>
                {
                    b.HasOne("ERP.Domain.Models.Customer", "Customer")
                        .WithMany("Payments")
                        .HasForeignKey("CustomerId");

                    b.HasOne("ERP.Domain.Models.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ERP.Domain.Models.Product", b =>
                {
                    b.HasOne("ERP.Domain.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ERP.Domain.Models.Purchase", b =>
                {
                    b.HasOne("ERP.Domain.Models.ApplicationUser", "CreatedByUser")
                        .WithMany("Purchases")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Models.Supplier", "Supplier")
                        .WithMany("Purchases")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ERP.Domain.Models.PurchaseItem", b =>
                {
                    b.HasOne("ERP.Domain.Models.Product", "Product")
                        .WithMany("PurchaseItem")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Models.Purchase", "Purchase")
                        .WithMany("PurchaseDetails")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ERP.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ERP.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ERP.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ERP.Domain.Models.ApplicationUser", b =>
                {
                    b.Navigation("InventoryLogs");

                    b.Navigation("Orders");

                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("ERP.Domain.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ERP.Domain.Models.Customer", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("ERP.Domain.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("ERP.Domain.Models.Product", b =>
                {
                    b.Navigation("InventoryLogs");

                    b.Navigation("OrderItem");

                    b.Navigation("PurchaseItem");
                });

            modelBuilder.Entity("ERP.Domain.Models.Purchase", b =>
                {
                    b.Navigation("PurchaseDetails");
                });

            modelBuilder.Entity("ERP.Domain.Models.Supplier", b =>
                {
                    b.Navigation("Purchases");
                });
#pragma warning restore 612, 618
        }
    }
}
